---running the whole table
SELECT * 
FROM `workspace`.`default`.`bright_coffee_shop_analysis_case_study_1_1`;


---checking the first 50 rows
SELECT * 
FROM `workspace`.`default`.`bright_coffee_shop_analysis_case_study_1_1`
LIMIT 50;


---checking our different store locations
SELECT DISTINCT store_location
FROM `workspace`.`default`.`bright_coffee_shop_analysis_case_study_1_1`;


---checking the product categories in our stores
SELECT DISTINCT  product_category
FROM `workspace`.`default`.`bright_coffee_shop_analysis_case_study_1_1`;


---checking the types of products in our stores
SELECT DISTINCT product_type
FROM `workspace`.`default`.`bright_coffee_shop_analysis_case_study_1_1`;


---checking details of the products in our stores
SELECT DISTINCT product_detail
FROM `workspace`.`default`.`bright_coffee_shop_analysis_case_study_1_1`;


---checking transaction dates range
SELECT MIN(transaction_date) AS first_date_of_transaction,
       MAX(transaction_date) AS last_date_of_transaction
FROM `workspace`.`default`.`bright_coffee_shop_analysis_case_study_1_1`;


---checking if there are NULLS in our data
SELECT transaction_date,
       transaction_qty,
       unit_price
FROM `workspace`.`default`.`bright_coffee_shop_analysis_case_study_1_1`
WHERE transaction_date is NULL
OR transaction_qty is NULL
OR unit_price is NULL;


---checking for store locations WHERE they only sell coffee
SELECT store_location,
       product_category
FROM `workspace`.`default`.`bright_coffee_shop_analysis_case_study_1_1`
WHERE product_category = 'Coffee';


---checking for the lowest and the highest unit price
SELECT MIN(unit_price) AS lowest_unit_price,
       MAX(unit_price) AS highet_unit_price
FROM `workspace`.`default`.`bright_coffee_shop_analysis_case_study_1_1`;


---counting the number of stores per location
SELECT store_location,
       COUNT(store_id) AS number_of_stores
FROM `workspace`.`default`.`bright_coffee_shop_analysis_case_study_1_1`
GROUP BY store_location;


---counting the number of products per category
SELECT product_category,
       COUNT(product_id) AS number_of_products
FROM `workspace`.`default`.`bright_coffee_shop_analysis_case_study_1_1`
GROUP BY product_category;


---calculating the revenue generated by our products
SELECT SUM(unit_price*transaction_qty) AS total_revenue
FROM `workspace`.`default`.`bright_coffee_shop_analysis_case_study_1_1`;


---calculating the top 5 most selling product categories
SELECT product_category,
       SUM(unit_price*transaction_qty) AS most_selling_category
FROM `workspace`.`default`.`bright_coffee_shop_analysis_case_study_1_1`
GROUP BY product_category
ORDER BY most_selling_category DESC
LIMIT 5;


---calculating average revenue per product category
SELECT product_category,
       AVG(unit_price*transaction_qty) AS average_revenue_per_category
FROM `workspace`.`default`.`bright_coffee_shop_analysis_case_study_1_1`
GROUP BY product_category;


---checking for stores that sells coffee or tea or coffee beans
SELECT store_location,
       product_category
FROM `workspace`.`default`.`bright_coffee_shop_analysis_case_study_1_1`
WHERE product_category IN ('Coffee','Tea','Coffee beans');



---checking for total revenue generated by either coffee or tea
SELECT product_category,
       SUM(unit_price*transaction_qty) AS total_revenue
FROM `workspace`.`default`.`bright_coffee_shop_analysis_case_study_1_1`
WHERE product_category = 'Coffee'
OR product_category = 'Tea'
OR product_category ='Coffee beans'
GROUP BY product_category;


---extracting the day and month names from the transaction dates
SELECT transaction_date,
       Dayname(transaction_date) AS day_name,
       Monthname(transaction_date) AS month_name
FROM `workspace`.`default`.`bright_coffee_shop_analysis_case_study_1_1`;


---adding new columns
SELECT transaction_id,
       transaction_date,
       transaction_time,
       transaction_qty,
       store_id,
       store_location,
       product_id,
       unit_price,
       product_category,
       product_type,
       product_detail,
---add the first new column
Dayname(transaction_date) AS day_name,
---add the second column
Monthname(transaction_date) AS month_name,
---add the third column
Dayofmonth(transaction_date) AS day_of_month,
---adding the fourth column
SUM(unit_price*transaction_qty) AS total_revenue,
---adding the fifth column
AVG(unit_price*transaction_qty) AS average_revenue_per_category,
CASE
    WHEN Dayname(transaction_date) = 'Sat' THEN 'Weekend'
    WHEN Dayname(transaction_date) = 'Sun' THEN 'Weekend'
    ELSE 'Weekday'
END AS Day_classification,
---Add time bucket range
CASE
    WHEN date_format(transaction_time, 'HH:mm:ss') BETWEEN '07:59:59' AND '08:59:59' THEN 'Early Rush hour'
    WHEN date_format(transaction_time, 'HH:mm:ss') BETWEEN '10:59:59' AND '11:59:59' THEN 'Morning rush'
    WHEN date_format(transaction_time, 'HH:mm:ss') BETWEEN '12:00:00' AND '13:59:59' THEN 'Lunch rush'
    WHEN date_format(transaction_time, 'HH:mm:ss') BETWEEN '15:59:59' AND '16:59:59' THEN 'Afternoon rush'
    WHEN date_format(transaction_time, 'HH:mm:ss') BETWEEN '17:00:00' AND '18:00:00' THEN 'Evening rush'
    ELSE 'Slow hours'
END AS classification_of_time
FROM `workspace`.`default`.`bright_coffee_shop_analysis_case_study_1_1`
GROUP BY transaction_id,
       transaction_date,
       transaction_time,
       transaction_qty,
       store_id,
       store_location,
       product_id,
       unit_price,
       product_category,
       product_type,
       product_detail;
